name: chekout repo
on: push
jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            run: echo "Checkout my repo"

          - name: get repos
            uses: actions/checkout@v4

          - name: List files 
            run: ls -la



