name: multi-job workflow

on: push

jobs:
 
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: install cowsay 
          run: sudo apt-get install cowsay -y

        - name: execute command 
          run: cowsay -f dragon "i am  a dragon" > dragon.txt

        - name: upload files 
          uses: actions/upload-artifact@v4
          with:
            name: dragon
            path: dragon.txt
        

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
        - name: upload files 
          uses: actions/download-artifact@v4
          with:
            name: dragon
            path: dragon.txt
  
        - name: grep file
          run: grep -i "dragon" dragon.txt


        
    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:
         - name: upload files 
           uses: actions/download-artifact@v4
           with:
            name: dragon
            path: dragon.txt

         - name: deploy job
           run: |
            cat  dragon.txt
            echo "deploy ........."
