name: secrets and variables

env: 
    DOCKER_USERNAME: mohamed
    CONTAINER_REGIESTRY: awsEcr
    IMAGE_NAME: nginx-latest

on: push

jobs: 

    docker: 
        runs-on: ubuntu-latest        
        steps:
        - name: docker build 
          run: echo docker build -t $CONTAINER_REGIESTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

        - name: docker login 
          run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASS }}

        - name: docker push 
          run: echo docker push -t $CONTAINER_REGIESTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
        



        
    deploy_job:
        needs: docker
        runs-on: ubuntu-latest
        steps:
         - name: Docker Run
           run:  echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest